#pragma once

#include <string>
#include <string_view>
#include <cstdint>
#include <vector>
#include <span>
#include <nlohmann/json.hpp>
#include "jwt/claims.hpp"
#include <nkeys/nkeys.hpp>

namespace jwt::internal {

/// Go's ClaimsData.Validate: exp/nbf against now, as TIME CHECKS.
void addTimeChecks(ValidationResults& vr, std::int64_t exp, std::int64_t nbf);

/// Throw the first blocking issue as InvalidClaimsError (the throwing
/// validate() built on the accumulating one).
void throwFirstBlocking(const ValidationResults& vr);

/// A SignFn over an in-process keypair (the encode(seed) path). The keypair
/// must outlive the returned function.
SignFn signerFor(const nkeys::KeyPair& kp);

/// Finish an encode (Go's doEncode tail): base64url the header and payload,
/// hand "header.payload" to the signer, VERIFY the returned signature against
/// issuerPublicKey (throws SignatureError on mismatch or bad length), and
/// assemble header.payload.signature.
std::string signAndAssemble(const std::string& payloadJson,
                            const std::string& issuerPublicKey,
                            const SignFn& sign);

/// Compute the claim ID the way Go's jwt does: SHA-512/256 over the claims
/// JSON serialized WITHOUT the jti field, base32-encoded without padding
/// (52 chars). Deterministic and content-derived; each library hashes its own
/// serialization, so values differ from Go's for the same logical claims.
/// @param payloadJsonWithoutJti the payload JSON, jti absent
/// @return 52-character base32 string
std::string computeJti(std::string_view payloadJsonWithoutJti);

/// Get current Unix timestamp in seconds
/// @return Unix timestamp (seconds since epoch)
std::int64_t getCurrentTimestamp();

/// Create JWT header as JSON string
/// @return JSON string: {"typ":"JWT","alg":"ed25519-nkey"}
std::string createHeader();

/// Parsed JWT components
struct JwtParts {
    std::string header_b64;
    std::string payload_b64;
    std::string signature_b64;
    std::string signing_input;  // "header.payload"
};

/// Go's Header.Valid: typ must be "JWT" case-insensitively; alg, lower-cased,
/// must be "ed25519" (v1) or "ed25519-nkey" (v2). Throws InvalidClaimsError.
void validateHeader(const std::string& headerJson);

/// The authenticated, version-migrated payload of a token (Go's Decode up to
/// loadClaims + signature verification):
///  - header per validateHeader;
///  - version: 1 if the payload has a top-level `type` (v1 layout), else
///    nats.version (Go: identifier.Version()); > 2 → "JWT was generated by a
///    newer version"; anything else but 1 or 2 → "library supports version 2
///    or less - received N";
///  - signature: version 1 is over the PAYLOAD chunk only, version 2 over
///    "header.payload"; verified against the embedded issuer;
///  - v1 payloads are migrated to the v2 layout (type/tags/issuer_account
///    moved into nats; activation import type "type" → "kind"; v1-only limit
///    fields dropped; user subs/data/payload default to -1 as Go's loader
///    presets NoLimit), with nats.version left at 1 as Go does.
struct Envelope {
    nlohmann::json payload;  ///< migrated to the v2 layout
    int version;             ///< 1 or 2
    std::string algorithm;   ///< the header's alg, lower-cased
};
Envelope decodeEnvelope(const std::string& token);

/// Parse JWT string into its components
/// @param jwt JWT string in format "header.payload.signature"
/// @return JwtParts structure with separated components
/// @throws std::invalid_argument if JWT format is invalid
JwtParts parseJwt(std::string_view jwt);

/// Verify JWT signature using Ed25519 public key
/// @param issuer_public_key Public key string (e.g., "OABC..." or "AABC...")
/// @param signing_input The "header.payload" string that was signed
/// @param signature_b64 Base64 URL encoded signature
/// @return true if signature is valid, false otherwise (malformed inputs
///         are false, never a throw)
bool verifySignature(const std::string& issuer_public_key,
                     const std::string& signing_input,
                     const std::string& signature_b64);

}

